/* DO NOT EDIT THIS FILE - it is machine generated */
#include "me_andrusiak_blinker_MainActivity.h"
/* Header for class me_andrusiak_blinker_MainActivity */
/*
 * Class:     me_andrusiak_blinker_MainActivity
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_andrusiak_blinker_MainActivity_getNativeString
  (JNIEnv *env, jobject obj){
      return (*env) -> NewStringUTF(env,"Hello from Native code");
  }