/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_andrusiak_blinker_MainActivity */

#ifndef _Included_me_andrusiak_blinker_MainActivity
#define _Included_me_andrusiak_blinker_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_andrusiak_blinker_MainActivity
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_andrusiak_blinker_MainActivity_getNativeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
